//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDWithImagesInMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class employee
    {
        public int id { get; set; }

        [DisplayName("Employee Name")]
        [Required(ErrorMessage = "Name is Required")]
        public string name { get; set; }

        [DisplayName("Employee Designation")]
        [Required(ErrorMessage = "Designation is Required")]
        public string designation { get; set; }

        [DisplayName("Employee Image")]

        //images path will be sotre in database
        public string image_path { get; set; }


        //acture image will store and that will sore in images folder
        // property name ImageFile should be same as butoon name (which is to upload image file)
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
